# FredMiner HiveOS Custom Miner manifest

CUSTOM_NAME="fredminer"
CUSTOM_VERSION="0.1.0"
CUSTOM_CONFIG_FILENAME="/hive/miners/custom/fredminer/fredminer.conf"
CUSTOM_LOG_BASENAME="/var/log/miner/fredminer/fredminer"
